# Generated by Django 5.1.3 on 2024-12-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default="Ma'lumot qo'shilmadi", verbose_name='Tavsifi'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Surati'),
        ),
    ]
