# Generated by Django 5.1.3 on 2024-12-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_products_description_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='description',
        ),
    ]
